# PyTorch


In [1]:
import torch
x = torch.rand(5, 3)
x

tensor([[0.6231, 0.8755, 0.0230],
        [0.0494, 0.0867, 0.2767],
        [0.3253, 0.4283, 0.2650],
        [0.9902, 0.9159, 0.2252],
        [0.9542, 0.2925, 0.6135]])

In [2]:
torch.cuda.is_available()

True

In [64]:
torch.cuda.current_device()

0

In [65]:
torch.cuda.device(0)

In [66]:
torch.cuda.device_count()

1

In [67]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 2080 Ti'

In [68]:
torch.__version__

'2.3.1+cu118'

In [69]:
torch.cuda.is_initialized()

True

In [70]:
torch.cuda.memory_allocated()

0

In [71]:
torch.cuda.memory_cached()

E:\Project\python\Lib\site-packages\torch\cuda\memory.py:440: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(


0

In [72]:
torch.cuda.memory_reserved()

0

In [73]:
torch.cuda.memory_snapshot()

[]

In [74]:
torch.cuda.memory_stats()

OrderedDict([('active.all.allocated', 0),
             ('active.all.current', 0),
             ('active.all.freed', 0),
             ('active.all.peak', 0),
             ('active.large_pool.allocated', 0),
             ('active.large_pool.current', 0),
             ('active.large_pool.freed', 0),
             ('active.large_pool.peak', 0),
             ('active.small_pool.allocated', 0),
             ('active.small_pool.current', 0),
             ('active.small_pool.freed', 0),
             ('active.small_pool.peak', 0),
             ('active_bytes.all.allocated', 0),
             ('active_bytes.all.current', 0),
             ('active_bytes.all.freed', 0),
             ('active_bytes.all.peak', 0),
             ('active_bytes.large_pool.allocated', 0),
             ('active_bytes.large_pool.current', 0),
             ('active_bytes.large_pool.freed', 0),
             ('active_bytes.large_pool.peak', 0),
             ('active_bytes.small_pool.allocated', 0),
             ('active_bytes.

In [75]:
x = torch.empty(5, 3)
x

tensor([[-4.1253e+11,  2.0095e-42,  1.4013e-45],
        [ 0.0000e+00,  1.4013e-45,  0.0000e+00],
        [ 1.4013e-45,  0.0000e+00,  1.4013e-45],
        [ 0.0000e+00,  1.4013e-45,  0.0000e+00],
        [ 1.4013e-45,  0.0000e+00,  1.4013e-45]])

In [76]:
x = torch.rand(5, 3)
x

tensor([[0.9300, 0.7894, 0.7676],
        [0.1444, 0.7799, 0.8943],
        [0.3974, 0.5745, 0.0143],
        [0.0892, 0.5473, 0.2371],
        [0.7723, 0.3071, 0.8905]])

In [77]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [78]:
x= torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [79]:
x = x.new_ones(5, 3, dtype=torch.double)

x = torch.randn_like(x, dtype=torch.float)
x

tensor([[ 0.6959, -0.4286,  0.1537],
        [ 0.7188,  0.4268,  0.6946],
        [-0.4722,  0.7672, -0.6627],
        [-0.3282,  0.4524, -0.0787],
        [-0.3267, -0.1129, -0.3021]])

In [80]:
x.size()

torch.Size([5, 3])

In [81]:
y = torch.rand(5, 3)
x + y

tensor([[ 1.1721,  0.3909,  0.2993],
        [ 0.7914,  0.5924,  1.6647],
        [-0.0983,  1.4719,  0.0563],
        [ 0.1429,  0.7162,  0.0305],
        [-0.1753,  0.1667,  0.4851]])

In [82]:
torch.add(x, y)

tensor([[ 1.1721,  0.3909,  0.2993],
        [ 0.7914,  0.5924,  1.6647],
        [-0.0983,  1.4719,  0.0563],
        [ 0.1429,  0.7162,  0.0305],
        [-0.1753,  0.1667,  0.4851]])

In [83]:
x[:, 1]

tensor([-0.4286,  0.4268,  0.7672,  0.4524, -0.1129])

In [84]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
x.size(), y.size(), z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [85]:
a = torch.ones(5)
b= a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [86]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [87]:
import datetime
datetime.datetime.now().hour

14

In [88]:
from lunarcalendar import Converter, Solar, Lunar
today=datetime.date.today()

 # 将当前日期转换为 Solar 对象
solar_date=Solar(today.year,today.month,today.day)

# 将 Solar 对象转换为 Lunar 对象
lunar_date=Converter.Solar2Lunar(solar_date)

In [89]:
lunar_date

Lunar(year=2024, month=5, day=3, isleap=False)

In [90]:
lunar_date.month

5

In [91]:
7%6

1

In [92]:
for i in range(1, 13):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


自动求导

In [93]:
#方法一
x = torch.randn(3,4, requires_grad=True)
x

tensor([[ 0.0946,  0.1056,  1.2599,  0.0394],
        [-0.1622,  0.7588, -0.4899,  0.7050],
        [ 0.3123,  0.0712, -0.9298,  1.0771]], requires_grad=True)

In [94]:
#方法二
x = torch.randn(3,4)
x.requires_grad_(True)
x

tensor([[ 0.5973,  0.9401, -0.8159, -0.4134],
        [ 0.9832, -1.4518, -1.1946, -0.4366],
        [ 0.7734,  0.1210,  1.0522,  2.1438]], requires_grad=True)

In [95]:
b = torch.randn(3,4, requires_grad=True)


In [96]:
t = x + b

In [97]:
y = t.sum()
y

tensor(6.0347, grad_fn=<SumBackward0>)

In [98]:
y.backward()

In [99]:
b.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [100]:
x.requires_grad, b.requires_grad, t.requires_grad

(True, True, True)

In [101]:
#计算流程
x = torch.rand(1)
b = torch.rand(1, requires_grad=True)
w = torch.rand(1, requires_grad=True)
y = w * x
z = y + b

In [102]:
x.requires_grad, b.requires_grad, w.requires_grad, y.requires_grad, z.requires_grad

(False, True, True, True, True)

In [103]:
x.is_leaf, b.is_leaf, w.is_leaf, y.is_leaf, z.is_leaf

(True, True, True, False, False)

反向传播计算

In [104]:
z.backward(retain_graph=True)

In [105]:
w.grad

tensor([0.4112])

In [106]:
b.grad

tensor([1.])

In [107]:
#清空梯度
w.grad.zero_()
b.grad.zero_()


tensor([0.])

做一个线性回归

构造一组输入数据x和其对应的标签y

In [108]:
x_values = [i for i in range(11)]
x_train = np.array(x_values, dtype=np.float32)
x_train = x_train.reshape(-1, 1)
x_train.shape

(11, 1)

In [109]:
y_values = [2*i + 1 for i in x_values]
y_train = np.array(y_values, dtype=np.float32)
y_train = y_train.reshape(-1, 1)
y_train.shape

(11, 1)

In [110]:
import torch.nn as nn

#线性回归模型
- 理论上就是一个没有激活函数的全连接层

In [111]:
class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegressionModel, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)#构造一个全连接层
        
    def forward(self, x):#定义前向传播规则
        out = self.linear(x)
        return out
        
    

In [141]:
input_dim = 1
output_dim = 1

model = LinearRegressionModel(input_dim, output_dim)#实例化模型

In [142]:
model

LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

指定参数和损失函数

In [143]:
epochs = 1000#训练次数
learning_rate = 0.01#学习率
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)#优化器
criterion = nn.MSELoss()#损失函数

训练模型

In [146]:



for epoch in range(epochs):#训练1000次
    epoch += 1#每次训练次数加1
    inputs = torch.from_numpy(x_train)#将numpy数组转换为张量
    labels = torch.from_numpy(y_train)#将numpy数组转换为张量
    
    optimizer.zero_grad()#清空梯度
    
    outputs = model(inputs)#前向传播
    
    loss = criterion(outputs, labels)#计算损失
    
    loss.backward()#反向传播
    
    optimizer.step()#更新参数
    
    if epoch % 50 == 0:
    
        print('epoch {}, loss {}'.format(epoch, loss.item()))



epoch 50, loss 2.3918545366541366e-07
epoch 100, loss 1.3648518404352217e-07
epoch 150, loss 7.772601406941249e-08
epoch 200, loss 4.435213796227799e-08
epoch 250, loss 2.5292386851560877e-08
epoch 300, loss 1.4382459667672265e-08
epoch 350, loss 8.237687865175758e-09
epoch 400, loss 4.723560209640709e-09
epoch 450, loss 2.669160226176359e-09
epoch 500, loss 1.5373884387770431e-09
epoch 550, loss 8.724793110204132e-10
epoch 600, loss 5.241751477313983e-10
epoch 650, loss 2.870708948332634e-10
epoch 700, loss 1.835112201087341e-10
epoch 750, loss 1.0753224699566744e-10
epoch 800, loss 5.093170329928398e-11
epoch 850, loss 3.915478011262685e-11
epoch 900, loss 3.915478011262685e-11
epoch 950, loss 3.915478011262685e-11
epoch 1000, loss 3.915478011262685e-11


In [147]:
predicted = model(torch.from_numpy(x_train).requires_grad_()).data.numpy()
predicted

array([[ 1.0000117],
       [ 3.00001  ],
       [ 5.000008 ],
       [ 7.0000067],
       [ 9.000005 ],
       [11.000003 ],
       [13.000001 ],
       [14.999999 ],
       [16.999998 ],
       [18.999996 ],
       [20.999994 ]], dtype=float32)

保存模型

In [148]:
torch.save(model.state_dict(), 'model.pkl')

In [149]:
model.load_state_dict(torch.load('model.pkl'))

<All keys matched successfully>

使用gpu

In [150]:
torch.cuda.is_available()

True

In [151]:
import torch
import torch.nn as nn
import numpy as np

class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegressionModel, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)
        
    def forward(self, x):
        out = self.linear(x)
        return out
    
input_dim = 1
output_dim = 1

model = LinearRegressionModel(input_dim, output_dim)

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model.to(device)

criterion = nn.MSELoss()

learning_rate = 0.01

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

epochs = 1000

for epoch in range(epochs):
    epoch += 1
    inputs = torch.from_numpy(x_train).to(device)
    labels = torch.from_numpy(y_train).to(device)
    
    optimizer.zero_grad()
    
    outputs = model(inputs)
    
    loss = criterion(outputs, labels)
    
    loss.backward()
    
    optimizer.step()
    
    if epoch % 50 == 0:
        print('epoch {}, loss {}'.format(epoch, loss.item()))

    

epoch 50, loss 9.75021393969655e-05
epoch 100, loss 5.561267971643247e-05
epoch 150, loss 3.1718111131340265e-05
epoch 200, loss 1.80902388819959e-05
epoch 250, loss 1.0318400200048927e-05
epoch 300, loss 5.885101472813403e-06
epoch 350, loss 3.3572348456800682e-06
epoch 400, loss 1.9145784335705684e-06
epoch 450, loss 1.0919017086052918e-06
epoch 500, loss 6.227760991350806e-07
epoch 550, loss 3.552141549789667e-07
epoch 600, loss 2.0269787626148172e-07
epoch 650, loss 1.1567685476165934e-07
epoch 700, loss 6.589525725075873e-08
epoch 750, loss 3.7615656367506745e-08
epoch 800, loss 2.1458355092818238e-08
epoch 850, loss 1.2188206000018909e-08
epoch 900, loss 6.9604406682799436e-09
epoch 950, loss 3.9764258552565934e-09
epoch 1000, loss 2.276919985888526e-09


In [152]:
predicted = model(torch.from_numpy(x_train).requires_grad_().to(device)).data.cpu().numpy()
predicted

array([[ 0.9999113],
       [ 2.9999242],
       [ 4.999937 ],
       [ 6.99995  ],
       [ 8.999963 ],
       [10.999975 ],
       [12.999989 ],
       [15.000002 ],
       [17.000015 ],
       [19.000027 ],
       [21.00004  ]], dtype=float32)

In [153]:
torch.save(model.state_dict(), 'model_gpu.pkl')


In [154]:
model.load_state_dict(torch.load('model_gpu.pkl'))

<All keys matched successfully>

In [155]:
model.eval()

LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

# 常见Tensor形式
- 0:scalar
- 1:vector
- 2:matrix
- 3:n-dimensional tensor

In [156]:
import torch
from torch import tensor

## 0:scalar
- 通常是一个数值

In [158]:
x = tensor(42.)
x

tensor(42.)

In [159]:
x.dim()

0

In [160]:
2*x

tensor(84.)

In [161]:
x.item()

42.0

## 1:vector

In [162]:
v = tensor([1.5, -0.5, 3.0])
v

tensor([ 1.5000, -0.5000,  3.0000])

In [163]:
v.dim()

1

In [164]:
v.size()

torch.Size([3])

## 2:matrix
- 一般计算的都是矩阵

In [166]:
m = tensor([[1., 2.], [3., 4.]])
m

tensor([[1., 2.],
        [3., 4.]])

In [167]:
m.dim()

2

In [168]:
m.size()

torch.Size([2, 2])

In [169]:
m[0, 1]

tensor(2.)

In [170]:
m[:, 0]

tensor([1., 3.])

In [171]:
m + tensor([10, 20])

tensor([[11., 22.],
        [13., 24.]])

In [172]:
m.matmul(m)

tensor([[ 7., 10.],
        [15., 22.]])

## 3:n-dimensional tensor

# Hub

In [173]:
import torch
model = torch.hub.load('pytorch/vision:v0.6.0', 'resnet18', pretrained=True)
model.eval()

Downloading: "https://github.com/pytorch/vision/zipball/v0.6.0" to C:\Users\Alexliang/.cache\torch\hub\v0.6.0.zip
Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to C:\Users\Alexliang/.cache\torch\hub\checkpoints\resnet18-5c106cde.pth
100.0%


ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  